export const PUB_SUB_EVENTS = {
	MESSAGE: {
		ADDED: 'MESSAGE:ADDED',
	},
	ACCOUNT: {
		ADDED: 'ACCOUNT:ADDED',
	},
  USER: {
		ADDED: 'USER:ADDED',
	},
  LEDGER: {
		ADDED: 'LEDGER:ADDED',
	},
  PIX_TRANSACTION: {
		ADDED: 'PIX_TRANSACTION:ADDED',
	},
} as const;
